(() => {
  'use strict';
  const data=window.STORY_CATALOG, $=id=>document.getElementById(id);
  const state={query:'',topic:''};let visible=[],readingId='',lastTrigger=null;
  function el(tag,cls,text){const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x;}
  function reset(){state.query='';state.topic='';$('searchInput').value='';render();}
  function makeTopics(){for(const name of ['전체 주제',...data.topics]){const b=el('button','topic',name);b.type='button';b.dataset.topic=name==='전체 주제'?'':name;b.onclick=()=>{state.topic=b.dataset.topic;render();};$('topics').append(b);}}
  function card(e){const a=el('article','story');const b=el('button','image-button');b.type='button';b.setAttribute('aria-label',e.title+' 크게 읽기');const img=el('img');img.src=e.image;img.alt=e.names.join(' · ')+'의 「'+e.title+'」 4컷 만화';img.loading='lazy';img.decoding='async';img.width=e.width;img.height=e.height;b.append(img);b.onclick=()=>open(e.id,b);a.append(b);const c=el('div','card-text'),meta=el('div','card-meta');meta.append(el('span','topic-label',e.topics[0]),el('span','',e.displayPerson||e.names.join(' · ')));const title=el('button','card-title',e.title);title.type='button';title.onclick=()=>open(e.id,title);c.append(meta,title,el('p','',e.message));a.append(c);return a;}
  function render(){visible=StorySearch.filter(data.episodes,state);$('stories').replaceChildren(...visible.map(card));document.querySelectorAll('[data-topic]').forEach(b=>{b.classList.toggle('active',b.dataset.topic===state.topic);b.setAttribute('aria-pressed',b.dataset.topic===state.topic);});$('resultTitle').textContent=state.query?'「'+state.query+'」 검색 결과':state.topic||'모든 이야기';$('resultCount').textContent=visible.length+'편 / 수록 '+data.episodes.length+'편';$('empty').hidden=!!visible.length;const noStoryPeople=data.people.filter(person=>!data.episodes.some(e=>e.sourceId===person.id));const searchedPerson=state.query&&noStoryPeople.find(person=>[person.label,...(person.names||[]),...(person.aliases||[])].some(name=>StorySearch.normalize(name).includes(StorySearch.normalize(state.query))));$('emptyText').textContent=searchedPerson?'이 채록의 기존 작품은 이번 선별 기준과 맞지 않아 수록하지 않았습니다. 자세한 이유는 선별 안내와 전체 선별 기록에서 확인할 수 있습니다.':'이름이나 작품 제목을 바꾸거나, 주제 선택을 해제해 보세요.';$('emptyReviewLink').hidden=!searchedPerson;}
  function open(id,trigger){const e=data.episodes.find(x=>x.id===id);if(!e)return;readingId=id;if(trigger)lastTrigger=trigger;$('readerTitle').textContent=e.title;$('readerPerson').textContent=e.sourceLabel;$('readerTopic').textContent=e.topics.join(' · ');$('readerMessage').textContent=e.message;$('readerImage').src=e.image;$('readerImage').alt=e.names.join(' · ')+'의 「'+e.title+'」 4컷 만화';$('downloadImage').href=e.image;$('downloadImage').download=e.title+'.png';$('sourceFile').textContent=e.sourceFiles.join(' · ');$('evidenceList').replaceChildren(...e.evidence.map(r=>{const block=el('div','evidence');block.append(el('cite','',[...(e.sourceFiles.length>1?[r.sourceFile]:[]),r.paragraph,r.speaker,r.time].filter(Boolean).join(' · ')),el('blockquote','',r.quote));return block;}));window.StoryContextUI?.renderEpisode(e);const index=visible.findIndex(x=>x.id===id);$('readerPosition').textContent=(index+1)+' / '+visible.length;$('previousStory').disabled=index<=0;$('nextStory').disabled=index>=visible.length-1;if(!$('reader').open)$('reader').showModal();$('reader').scrollTop=0;}
  function move(n){const index=visible.findIndex(x=>x.id===readingId),next=visible[index+n];if(next)open(next.id);}
  makeTopics();$('searchInput').addEventListener('input',()=>{state.query=$('searchInput').value;state.topic='';render();});$('resetButton').onclick=reset;$('emptyReset').onclick=reset;$('closeReader').onclick=()=>$('reader').close();$('reader').addEventListener('close',()=>lastTrigger?.focus());$('reader').addEventListener('click',event=>{if(event.target===$('reader')){const r=$('reader').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('reader').close();}});$('previousStory').onclick=()=>move(-1);$('nextStory').onclick=()=>move(1);$('reader').addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);});$('collectionCount').append(el('strong','',data.episodes.length+'편'),el('span','',data.provisional?'검토 완료 작품':'선별한 이야기'));$('footerCount').textContent='수록 '+data.episodes.length+'편 · 검토 '+data.reviewedCount+'편';if(data.provisional){$('reviewNotice').hidden=false;$('reviewNotice').textContent='원문 검토를 마친 작품으로 먼저 구성한 미리보기입니다. 나머지 작품을 검토해 목록을 완성하고 있습니다.';}render();
})();
